//////
//////  FilmModel.swift
//////  CineFiles
//////
//////  Created by Andre Castilhano on 29/05/25.
//////
import Foundation

struct Filme: Identifiable {
    var id = UUID()
    var image: String
    var titulo: String
    var sinopse: String
    var direcao: String
    var roteristas: String
    var ano: Int
    var duracao: Int
    var isFavorite: Bool
    var isWatched: Bool
}

extension Array where Element == Filme {
    static func filmes() -> [Filme] { [
        Filme(image: "filme1", titulo: "Tudo em Todo o Lugar ao Mesmo Tempo", sinopse: "Uma imigrante chinesa de meia idade se envolve em uma aventura louca, onde só ela pode salvar o mundo explorando outros universos que se conectam com as vidas que ela poderia ter levado", direcao: "Daniel Kwan, Daniel Scheinert", roteristas: "Daniel Kwan, Daniel Scheinert", ano: 2022, duracao: 139, isFavorite: false, isWatched: false),
        Filme(image: "filme2", titulo: "Cisne negro", sinopse: "Uma esforçada bailarina luta para manter sua sanidade após obter o papel principal no Lago dos Cisnes de Tchaikovsky.", direcao: "Darren Aronofsky", roteristas: "Mark Heyman, Andres Heinz, John J. McLaughlin", ano: 2010, duracao: 108, isFavorite: false, isWatched: false),
        Filme(image: "filme3", titulo: "Barbie a princesa e a plebeia", sinopse: "Uma plebeia, moradora de um vilarejo, é muito parecida com a princesa do reino. Os destinos das duas se cruzam quando a princesa é sequestrada, e a moça humilde usa sua incrível semelhança com ela para tentar salvar das mãos do vilão.", direcao: "William Lau", roteristas: "Cliff Ruby, Elana Lesser, Ruth Handler", ano: 2004, duracao: 85, isFavorite: false, isWatched: false),
        Filme(image: "filme4", titulo: "Show de Truman", sinopse: "Truman Burbank é um pacato vendedor de seguros que leva uma vida simples com sua esposa Meryl Burbank. Porém, algumas coisas ao seu redor fazem com que ele passe a estranhar sua cidade, seus supostos amigos e até sua mulher. Após conhecer a misteriosa Lauren, ele fica intrigado e acaba descobrindo que toda sua vida foi monitorada por câmeras e transmitida em rede nacional.", direcao: "Peter Weir", roteristas: "Peter Weir, Andrew Niccol", ano: 1998, duracao: 103, isFavorite: false, isWatched: false),
        Filme(image: "filme5", titulo: "Spirit: O Corcel Indomável", sinopse: "Animação sobre a amizade entre um menino indígena e um cavalo indomável apaixonado por uma égua. Ambientada no Velho Oeste americano, mostra o impacto do processo civilizatório na vida dos três e também na amizade que construíram.", direcao: "Kelly Asbury, Lorna Cook", roteristas: "John Fusco", ano: 2002, duracao: 83, isFavorite: false, isWatched: false),
        Filme(image: "filme6", titulo: "Labirinto do Fauno", sinopse: "Em 1944, na Espanha, a jovem Ofélia e sua mãe doente chegam ao posto do novo marido de sua mãe, um sádico oficial do exército que está tentando reprimir uma guerrilheira. Enquanto explorava um labirinto antigo, Ofélia encontra o Pan fauno, que diz que a menina é uma lendária princesa perdida e que ela precisa completar três tarefas perigosas a fim de se tornar imortal.", direcao: "Guillermo del Toro", roteristas: "Guillermo del Toro", ano: 2006, duracao: 119, isFavorite: false, isWatched: false),
        Filme(image: "filme7", titulo: "O Predestinado", sinopse: "Um agente precisa viajar no tempo para impedir a ação de um criminoso responsável por um ataque que mata milhares de pessoas.", direcao: "Michael Spierig, Peter Spierig", roteristas: "Michael Spierig, Peter Spierig, Robert A Heinlein (autor da obra original)", ano: 2015, duracao: 97, isFavorite: false, isWatched: false),
        Filme(image: "filme8", titulo: "Gigantes de aço", sinopse: "Em um futuro próximo, as máquinas substituem os homens no ringue. As lutas de boxe acontecem entre robôs de alta tecnologia. Charlie, um ex-lutador frustrado, decide se juntar ao filho para construir um competidor imbatível.", direcao: "Shawn Levy", roteristas: "Dan Gilroy, Les Bohem, Jeremy Leven, John Gatins, Richard Matheson (autor da obra original)", ano: 2011, duracao: 127, isFavorite: false, isWatched: false),
        Filme(image: "filme9", titulo: "A vastidão da noite", sinopse: "Duas crianças procuram a fonte de uma misteriosa frequência que surgiu em sua cidade.", direcao: "Andrew Patterson", roteristas: "James Montague, Craig W. Sanger", ano: 2019, duracao: 91, isFavorite: false, isWatched: false),
        Filme(image: "filme10", titulo: "Parasita", sinopse: "Toda a família de Ki-taek está desempregada, vivendo em um porão sujo e apertado. Por obra do acaso, ele começa a dar aulas de inglês para uma garota de família rica. Fascinados com a vida luxuosa destas pessoas, pai, mãe e filhos bolam um plano para se infiltrar também na abastada família, um a um. No entanto, os segredos e mentiras necessários à ascensão social cobram o seu preço.", direcao: "Bong Joon-ho", roteristas: "Bong Joon-ho, Jin Won Han", ano: 2019, duracao: 132, isFavorite: false, isWatched: false),
        Filme(image: "filme11", titulo: "Passivonas", sinopse: "Duass alunas não populares do último ano do ensino médio criam um clube da luta para tentar impressionar e conquistar líderes de torcida.", direcao: "Emma Seligman", roteristas: "Emma Seligman, Rachel Sennott", ano: 2023, duracao: 92, isFavorite: false, isWatched: false),
        Filme(image: "filme12", titulo: "Turma da Mônica: Uma Aventura no Tempo", sinopse: "Franjinha está construindo uma máquina do tempo e precisa reunir moléculas dos quatro elementos: ar, água, fogo e terra. Mônica joga Sansão e, sem querer, acerta o aparelho, espalhando os elementos. Agora a turma precisa consertá-la.", direcao: "Mauricio de Sousa", roteristas: "Mauricio de Sousa, Flávio de Souza, Didi Oliveira, Emerson Bernardo de Abreu", ano: 2007, duracao: 80, isFavorite: false, isWatched: false),
        Filme(image: "filme13", titulo: "Amnésia (Memento)", sinopse: "Leonard está caçando o homem que estuprou e matou sua esposa. Ele tem dificuldades em encontrar o assassino pois sofre de uma forma intratável de perda de memória. Mesmo que ele possa lembrar detalhes da vida antes do acidente, Leonard não consegue lembrar o que aconteceu quinze minutos atrás, onde está indo ou a razão.", direcao: "Christopher Nolan", roteristas: "Christopher Nolan, Jonathan Nolan", ano: 2001, duracao: 114, isFavorite: false, isWatched: false),
        Filme(image: "filme14", titulo: "Os Excêntricos Tenenbaums", sinopse: "Royal e sua esposa Etheline tiveram três filhos muito diferentes entre si, mas igualmente bem-sucedidos. Quando Etheline resolve se casar com outro, o irresponsável e excêntrico Royal resolve lutar por seu amor reunindo toda a família.", direcao: "Wes Anderson", roteristas: "Wes Anderson, Owen Wilson", ano: 2002, duracao: 109, isFavorite: false, isWatched: false),
        Filme(image: "filme15", titulo: "La la Land", sinopse: "O pianista Sebastian conhece a atriz Mia, e os dois se apaixonam perdidamente. Em busca de oportunidades para suas carreiras na competitiva Los Angeles, os jovens tentam fazer o relacionamento amoroso dar certo, enquanto perseguem fama e sucesso.", direcao: "Damien Chazelle", roteristas: "Damien Chazelle", ano: 2017, duracao: 128, isFavorite: false, isWatched: false),
        Filme(image: "filme16", titulo: "Os Serviços de Entrega da Kiki", sinopse: "Por ordem de sua mãe, Kiki parte para um aprendizado de um ano, acompanhada por seu gato preto. A um comando de sua vassoura mágica, ela vai parar na charmosa cidadezinha de Moreoastal. Infelizmente, os hotéis locais não aceitam bruxas e a polícia a flagra fazendo algumas travessuras.", direcao: "Hayao Miyazaki", roteristas: "Hayao Miyazaki, Jack Fletcher, John Semper", ano: 1990, duracao: 102, isFavorite: false, isWatched: false),
        Filme(image: "filme17", titulo: "O Feitiço de Áquila", sinopse: "O ladrão Gaston escapa da masmorra medieval de Aquila através da latrina. Os soldados estão prestes a matá-lo quando Navarra o salva. Navarra, viajando com seu falcão animado, planeja matar o bispo de Áquila com a ajuda de Gaston.", direcao: "Richard Donner", roteristas: "Michael Thomas, Tom Mankiewicz", ano: 1985, duracao: 121, isFavorite: false, isWatched: false),
        Filme(image: "filme18", titulo: "Os Incríveis", sinopse: "Depois do governo banir o uso de superpoderes, o maior herói do planeta, o Sr. Incrível, vive de forma pacata com sua família. Apesar de estar feliz com a vida doméstica, o Sr. Incrível ainda sente falta dos tempos em que viveu como super-herói, e sua grande chance de entrar em ação novamente surge quando um velho inimigo volta a atacar. Só que agora ele precisa contar com a ajuda de toda a família para vencer o vilão.", direcao: "Brad Bird", roteristas: "Brad Bird", ano: 2004, duracao: 123, isFavorite: false, isWatched: false),
    ]
    }
}
